# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.6
    build: .
    # uncomment these if you are having this issue with the build:
    # /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/site.rb:509:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/.jekyll-cache/.gitignore (Errno::EACCES)
    # and fill the args values with the output of the commands on the right
    # build:
    #   args:
    #     GROUPID: 1000
    #     GROUPNAME: ccchan
    #     USERID: 1000
    #     USERNAME: ccchan
    ports:
      - 8082:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - gem_cache:/usr/local/bundle/
    environment:
      - JEKYLL_ENV=development
    command:  sh -c "bundle install && bundle exec jekyll serve --watch --livereload --livereload-port 35729 --force_polling --host 0.0.0.0 --port 8080"
volumes:
  gem_cache:
